# /api/app/core/domain/models.py
"""
Domain Models - AIbrarian

This file defines the project's data structures (entities). In
hexagonal architecture, the domain is the core that does NOT depend on
anything external.

We use Pydantic for:
- Automatic data validation
- JSON serialization
- Automatic Swagger/OpenAPI documentation

TypeScript equivalent: interfaces + Zod for validation
"""

# ============================================================================
# IMPORTS
# ============================================================================
from typing import List, Optional, Dict, Any  # Python types (like TypeScript types)
from datetime import datetime                  # For handling dates and timestamps
from pydantic import BaseModel, Field          # Pydantic: schema validation (like Zod in JS)
from enum import Enum                          # For creating enumerations (fixed types)


# ============================================================================
# ENUMERATIONS
# ============================================================================
class DocumentSource(str, Enum):
    """
    Supported document source types.

    Inherits from (str, Enum) so the values are serializable strings.

    TypeScript equivalent:
        enum DocumentSource {
            PDF = "pdf",
            NOTION = "notion",
            TEXT = "text"
        }
    """
    PDF = "pdf"        # Local PDF documents
    NOTION = "notion"  # Notion pages
    TEXT = "text"      # Plain text


# ============================================================================
# MAIN ENTITIES
# ============================================================================
class Document(BaseModel):
    """
    Represents a complete document (PDF or Notion page).

    This is the main entity loaded from the sources. A Document is
    split into multiple Chunks for RAG processing.

    Attributes:
        id: Unique identifier (generated with UUID)
        source: Source type (pdf, notion, text)
        content: Full text extracted from the document
        metadata: Additional info (filename, pages, URL, etc.)
        created_at: Creation/ingestion date

    TypeScript equivalent:
        interface Document {
            id: string;
            source: DocumentSource;
            content: string;
            metadata?: Record<string, any>;
            created_at?: Date;
        }
    """
    # Field(...) = required field (the ... means "required")
    # Field(default=X) = optional field with a default value

    id: str = Field(..., description="Unique document identifier")
    source: DocumentSource = Field(..., description="Source type (pdf, notion, text)")
    content: str = Field(..., description="Full text content of the document")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,  # default_factory=dict creates a new {} for each instance
        description="Additional metadata (filename, page_count, url, etc.)"
    )
    created_at: datetime = Field(
        default_factory=datetime.now,  # Generated automatically on creation
        description="Creation timestamp"
    )

    class Config:
        """Pydantic configuration for this model."""
        json_schema_extra = {
            "example": {
                "id": "doc_123",
                "source": "pdf",
                "content": "This is the document's content...",
                "metadata": {"filename": "manual.pdf", "page_count": 10}
            }
        }


class Chunk(BaseModel):
    """
    Represents a fragment of text from a document.

    Why split into chunks?
    - LLMs have a limited context window (tokens)
    - Vector search works better with short texts
    - Lets you find specific relevant sections

    A chunk is typically 500-1000 characters with a 100-200 char overlap.

    Attributes:
        id: Unique chunk identifier (e.g. "doc_123_chunk_0")
        document_id: Reference to the parent document
        content: The fragment's text
        embedding: Numeric vector representing the text's "meaning"
                   (a list of ~768 floats generated by the embedding model)
        metadata: Additional info (page number, position, etc.)
    """
    id: str = Field(..., description="Unique chunk identifier")
    document_id: str = Field(..., description="Parent document ID (foreign key)")
    content: str = Field(..., description="The fragment's text")
    embedding: Optional[List[float]] = Field(
        None,  # None = can be null/undefined
        description="Embedding vector (list of ~768 floats). Generated by the embedding model."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Chunk metadata (page, position, source_file, etc.)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "id": "chunk_456",
                "document_id": "doc_123",
                "content": "This is a text fragment from the document...",
                "metadata": {"page": 1, "position": 0}
            }
        }


# ============================================================================
# AUTHENTICATION
# ============================================================================
class User(BaseModel):
    """
    Represents a user with access to the system.

    There's no signup UI: users are created with scripts/create_user.py
    and stored in Postgres (Neon).

    IMPORTANT: password_hash is sensitive data. This model is used
    between the adapter and the services (internal layer) — it's never
    returned directly from an API endpoint. main.py defines its own
    UserResponse (without password_hash) for that, the same way it
    already separates HealthResponse from the domain models.

    Attributes:
        id: Unique identifier (auto-incrementing in Postgres)
        email: User's email, used as login
        password_hash: bcrypt hash of the password
        is_active: Whether the user can log in
        created_at: Account creation date

    TypeScript equivalent:
        interface User {
            id: number;
            email: string;
            passwordHash: string;
            isActive: boolean;
            createdAt: Date;
        }
    """
    id: int = Field(..., description="Unique user identifier (auto-incrementing)")
    email: str = Field(..., description="User's email, used as login")
    password_hash: str = Field(..., description="bcrypt hash of the password (sensitive data, never exposed in API responses)")
    is_active: bool = Field(default=True, description="Whether the user can log in")
    created_at: datetime = Field(
        default_factory=datetime.now,
        description="Account creation date"
    )


# ============================================================================
# QUERY MODELS (RAG SYSTEM INPUT/OUTPUT)
# ============================================================================
class Query(BaseModel):
    """
    Represents a user query/question to the RAG system.

    This is the INPUT for the POST /ask endpoint.

    Attributes:
        question: The natural-language question
        session_id: (Optional) To keep context across questions
        max_results: How many context chunks to retrieve (default: 4)

    Validations:
        - question: at least 1 character (can't be empty)
        - max_results: between 1 and 10 (ge=greater or equal, le=less or equal)
    """
    question: str = Field(
        ...,
        min_length=1,  # Validation: can't be empty
        description="User's question in natural language"
    )
    session_id: Optional[str] = Field(
        None,
        description="Session ID for contextual conversations (future)"
    )
    max_results: int = Field(
        default=4,
        ge=1,   # ge = greater or equal (>=)
        le=10,  # le = less or equal (<=)
        description="Maximum number of context chunks to retrieve"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "question": "What is the document's main topic?",
                "session_id": "session_789",
                "max_results": 4
            }
        }


class ConversationMessage(BaseModel):
    """
    Represents a turn (message) in a conversation's history.

    Persisted in Postgres (conversation_messages) by ConversationService,
    and used to give context from previous turns when generating an
    answer (see RAGService.ask_question and
    OllamaAdapter.generate_response).

    Attributes:
        role: "user" or "assistant"
        content: The message's text (question or answer)
        created_at: When the message was saved
    """
    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="The message's text")
    created_at: datetime = Field(..., description="When the message was saved")


class SourceDocument(BaseModel):
    """
    Represents a source used to generate an answer.

    When the system answers a question, it includes the sources it
    pulled the information from (for transparency and verification).

    Attributes:
        document_id: ID of the original document
        chunk_content: The chunk's text that was used as context
        metadata: Document info (filename, page, etc.)
        relevance_score: Similarity score (0-1, higher = more relevant)
    """
    document_id: str = Field(..., description="Source document ID")
    chunk_content: str = Field(..., description="Chunk text used as context")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Source metadata (filename, page, url, etc.)"
    )
    relevance_score: Optional[float] = Field(
        None,
        description="Relevance/similarity score (0.0 to 1.0)"
    )


class QueryResult(BaseModel):
    """
    Full result of a RAG query.

    This is the OUTPUT of the POST /ask endpoint.
    Includes both the generated answer AND the sources used.

    Attributes:
        question: The original question (echoed back)
        answer: Answer generated by the LLM
        source_documents: List of sources used to generate the answer
        session_id: Session ID (if provided)
        processing_time: Processing time in seconds
    """
    question: str = Field(..., description="Original question")
    answer: str = Field(..., description="Answer generated by the LLM")
    source_documents: List[SourceDocument] = Field(
        default_factory=list,
        description="Sources used to generate the answer"
    )
    session_id: Optional[str] = Field(None, description="Session ID")
    processing_time: Optional[float] = Field(
        None,
        description="Processing time in seconds"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "question": "What is RAG?",
                "answer": "RAG (Retrieval-Augmented Generation) is a technique that...",
                "source_documents": [
                    {
                        "document_id": "doc_123",
                        "chunk_content": "RAG is an AI technique that...",
                        "metadata": {"page": 1},
                        "relevance_score": 0.95
                    }
                ],
                "processing_time": 1.23
            }
        }


class DocumentSummary(BaseModel):
    """
    Summary of an indexed document, for listing it without going
    through similarity search (unlike SourceDocument, which represents
    a CHUNK used as context for a specific answer).

    It's the result of grouping all the chunks that share a document_id
    in the vector database. Used both in GET /documents (so the user
    can browse the knowledge base from the UI) and in RAGService to
    answer questions like "how many documents do you know?" without
    relying on semantic retrieval (see LLMPort.is_catalog_question).

    Attributes:
        document_id: Document ID (e.g. "notion_abc123", "pdf_a3f2b1c9")
        title: Human-readable title — from metadata.title/filename, or
               the document_id itself as a last-resort fallback
        source: "pdf" | "notion" | "unknown", inferred from the id's prefix
        chunk_count: How many chunks this document has in the collection
    """
    document_id: str = Field(..., description="Document ID")
    title: str = Field(..., description="Human-readable document title")
    source: str = Field(..., description="Document source: pdf, notion or unknown")
    chunk_count: int = Field(..., description="Number of chunks for this document in the collection")


# ============================================================================
# SYNC/INGESTION MODELS
# ============================================================================
class SyncResult(BaseModel):
    """
    Result of a document sync/ingestion operation.

    This is the OUTPUT of the POST /sync and POST /sync/notion endpoints.

    Attributes:
        document_id: ID of the processed document
        chunks_created: Number of chunks generated
        success: Whether the operation succeeded
        message: Informational or error message
        processing_time: Processing time in seconds
    """
    document_id: str = Field(..., description="ID of the processed document")
    chunks_created: int = Field(..., description="Number of chunks created")
    success: bool = Field(..., description="Whether the operation succeeded")
    message: Optional[str] = Field(
        None,
        description="Informational or error message"
    )
    processing_time: Optional[float] = Field(
        None,
        description="Processing time in seconds"
    )
