# /api/app/core/ports/conversation_repository_port.py
"""
Port (Interface) for the Conversation History Repository - AIbrarian

Defines the CONTRACT for persisting/querying the turns (messages) of a
conversation. Same pattern as UserRepositoryPort: an abstract interface
that doesn't know whether Postgres or anything else is behind it.

TypeScript equivalent:
    interface ConversationRepositoryPort {
        appendMessage(sessionId: string, userId: number, role: string, content: string): Promise<void>;
        getRecentMessages(sessionId: string, userId: number, limit: number): Promise<ConversationMessage[]>;
    }

The real implementation lives at: /adapters/outbound/postgres_conversation_adapter.py

Important contract detail (same as UserRepositoryPort): connection/DB
errors must propagate, not get silently translated into "no history" —
the caller (ConversationService / the /ask endpoint) decides how to
degrade (log and continue without history), not the port.
"""

from abc import ABC, abstractmethod
from typing import List

from app.core.domain.models import ConversationMessage


class ConversationRepositoryPort(ABC):
    """
    Abstract interface for storing conversation history.

    Minimal surface: only what ConversationService needs — append a
    message and retrieve the last N from a session.
    """

    @abstractmethod
    async def append_message(
        self,
        session_id: str,
        user_id: int,
        role: str,
        content: str
    ) -> None:
        """
        Saves a new conversation turn.

        Args:
            session_id: Session ID generated by the client
            user_id: ID of the authenticated user (scoping, see the adapter)
            role: "user" or "assistant"
            content: The message's text
        """
        pass

    @abstractmethod
    async def get_recent_messages(
        self,
        session_id: str,
        user_id: int,
        limit: int
    ) -> List[ConversationMessage]:
        """
        Retrieves the last `limit` messages of a session, in ascending
        chronological order (oldest first, ready to format as prompt
        history).

        Args:
            session_id: Session ID to query
            user_id: ID of the authenticated user (scoping, see the adapter)
            limit: Maximum number of messages to return

        Returns:
            List[ConversationMessage]: empty if the session has no messages
        """
        pass
