# /api/app/core/services/conversation_service.py
"""
Conversation History Service - AIbrarian

Persists and retrieves a conversation's turns, and formats them as a
text block ready to inject into the LLM's prompt (see
RAGService.ask_question / OllamaAdapter.generate_response).

Deliberately does NOT live inside RAGService: RAGService is documented
as needing exactly 2 ports (LLM + VectorDB) — adding a third would
break that contract and every place that instantiates
RAGService(llm=..., vector_db=...) (including the integration tests).
Instead, the /ask endpoint (main.py) composes both services: it fetches
the history before calling rag_service.ask_question(), and persists the
new turns afterward — the same "thin endpoints that orchestrate
services" pattern the rest of main.py already uses.

TypeScript equivalent:
    class ConversationService {
        constructor(private conversationRepository: ConversationRepositoryPort) {}
        async appendTurn(sessionId, userId, question, answer): Promise<void> { ... }
        async getHistoryPromptBlock(sessionId, userId): Promise<string> { ... }
    }
"""

from app.core.ports.conversation_repository_port import ConversationRepositoryPort
from app.config.settings import settings
from app.core.observability import get_logger

logger = get_logger(__name__)


class ConversationService:
    """
    Conversation history service: persists turns and formats them as
    context for the LLM's prompt.

    Only needs one port (ConversationRepositoryPort), same pattern as
    AuthService with UserRepositoryPort.
    """

    def __init__(self, conversation_repository: ConversationRepositoryPort):
        self.conversation_repository = conversation_repository

    async def append_turn(
        self,
        session_id: str,
        user_id: int,
        question: str,
        answer: str
    ) -> None:
        """
        Saves a full turn (user's question + assistant's answer) of the
        history.

        Args:
            session_id: Session ID generated by the client
            user_id: ID of the authenticated user
            question: The user's question
            answer: The generated answer (includes the error case — see
                    the /ask endpoint's docstring in main.py)
        """
        await self.conversation_repository.append_message(session_id, user_id, "user", question)
        await self.conversation_repository.append_message(session_id, user_id, "assistant", answer)

    async def get_history_prompt_block(self, session_id: str, user_id: int) -> str:
        """
        Retrieves the conversation's most recent turns and formats them
        as text, ready to prepend to the LLM's prompt.

        Format (same style as RAGService._build_context for sources, for
        consistency):
            User: What is RAG?
            Assistant: RAG combines retrieval with text generation...

            User: can you explain it with an example?
            Assistant: ...

        Args:
            session_id: Session ID to query
            user_id: ID of the authenticated user

        Returns:
            str: formatted history block, empty string if there are no
                 previous turns (settings.conversation_history_turns=0
                 also produces an empty string, without querying the DB)
        """
        if settings.conversation_history_turns <= 0:
            return ""

        # N turns = N user messages + N assistant messages
        limit = settings.conversation_history_turns * 2
        messages = await self.conversation_repository.get_recent_messages(session_id, user_id, limit)

        if not messages:
            return ""

        lines = []
        for message in messages:
            speaker = "User" if message.role == "user" else "Assistant"
            lines.append(f"{speaker}: {message.content}")

        return "\n\n".join(lines)
